### ISSUE TITLE
なんと条件分岐が多き事か

### ISSUE THREAD

**Issue by Yawn-MP** [c0b21107de/ProjExD#11]
https://github.com/c0b21107de/ProjExD/blob/51d54f59cc94f04ac6b4e2749c155d2bc8f6f7b5/ex03/maze.py#L36
ふしみりぽじとりをさんこうに、もっときれいにした方がいいかも

**Comment by c0b21107de** [comment]
コメントありがとうございます。先生のリポジトリを参考に修正いたしました。参考まで示していただきありがとうございました。
