### ISSUE TITLE
移動方法が賢い

### ISSUE THREAD

**Issue by c2cb** [c0b21107de/ProjExD#12]
https://github.com/c0b21107de/ProjExD/blob/3b3f308db4da0812c35f965b0331315a3ee303e4/ex03/maze.py#L32

移動方法をマスの手段にすることは思いつきませんでした。視野が広がりました、ありがとうございました。

**Comment by c0b21107de** [comment]
コメントありがとうございます。先生のリポジトリを参考にしましたので、ぜひ真似してみてください。
