### ISSUE TITLE
ゲームオーバーの表示ができてすごい

### ISSUE THREAD

**Issue by c2cb** [c0b21107de/ProjExD#13]
https://github.com/c0b21107de/ProjExD/blob/baecf73d0b8692dc025abb77866c23dd7c272d74/ex04/dodge_bomb.py#L21

自分も追加機能として取り入れましたが、ほとんど先生が丁寧に教えてくれたものです。
自分でできてすごいです、とても勉強になりました。

**Comment by c0b21107de** [comment]
コメントありがとうございます。関数を追加してやると便利なのでぜひ真似てみてください。
