### ISSUE TITLE
このあたり

### ISSUE THREAD

**Issue by RenNakasato** [c0b21107de/ProjExD#15]
https://github.com/c0b21107de/ProjExD/blob/12487102666a12c332325b6864f948a4ec2ee249/ex05/fight_kokaton.py#L245
コンティーニュー機能は考え付きませんでした。すごいと思いました。

**Comment by c0b21107de** [comment]
コメントありがとうございます。main関数で新たな関数を呼び出すことでコンテニューなどを実現しやすくしております。
