### ISSUE TITLE
説明の追加を

### ISSUE THREAD

**Issue by Yawn-MP** [c0b21107de/ProjExD#16]
https://github.com/c0b21107de/ProjExD/blob/12487102666a12c332325b6864f948a4ec2ee249/ex05/fight_kokaton.py#L81
クラスの説明や、その内部での処理について、おおざっぱでいいので書いてもらえると流れが見えやすくて良いと思います

**Comment by c0b21107de** [comment]
修正いたしました。コメントありがとうございます。
