### ISSUE TITLE
ゲームオーバーの表示ができてすごい！

### ISSUE THREAD

**Issue by c2cb** [c0b21107de/ProjExD#17]
https://github.com/c0b21107de/ProjExD/blob/12487102666a12c332325b6864f948a4ec2ee249/ex05/fight_kokaton.py#L179

ゲームの終了表示は前回一番てこずったところですので、軽々と実現させる技術力にはまた驚かされました！
ユーフォ―の動きにもこだわっている点や、当たった際の音の工夫も素晴らしいです…全部参考になります、これからも応援しています！

**Comment by c0b21107de** [comment]
コメントありがとうございます。新たな関数をmainで呼び出すことで容易に実現できますので是非お試しください。
