### ISSUE TITLE
文字コードの利用

### ISSUE THREAD

**Issue by c2cb** [c0b21107de/ProjExD#3]
https://github.com/c0b21107de/ProjExD/blob/aa541d9f53a9447155a42397fc01172a518e6bfa/ex01/alphabet.py#L15

アルファベットを一つづつ打ち込むことなく、文字コードを利用して省略する方法はとても賢いと思った。

**Comment by c0b21107de** [comment]
コメントありがとうございます。ぜひ文字コードをご利用くださいませ。
