### ISSUE TITLE
数字ではなく四則演算を押して計算を行う処理をするユーザーの想定ができていて、勉強になりました。

### ISSUE THREAD

**Issue by RenNakasato** [c0b21107de/ProjExD#6]
https://github.com/c0b21107de/ProjExD/blob/4fb7dd3fee6959ef0d1ef2fd98154c4a6beeaf2f/ex02/calc.py#L19

**Comment by c0b21107de** [comment]
コメントありがとうございます。警告文は工夫した点の一つだったので気づいていただきありがとうございます。
