### ISSUE TITLE
綺麗なコードでした

### ISSUE THREAD

**Issue by sugaikota** [c0b21107de/ProjExD#7]
https://github.com/c0b21107de/ProjExD/blob/4fb7dd3fee6959ef0d1ef2fd98154c4a6beeaf2f/ex02/calc.py#L32
簡潔にまとめられている綺麗なコードだと思いました。

**Comment by c0b21107de** [comment]
コメントありがとうございます。恥ずかしながらここのコードは先生のものを参考にしただけです。
