### ISSUE TITLE
細かい判定ができてすごい

### ISSUE THREAD

**Issue by c2cb** [c0b21107de/ProjExD#8]
https://github.com/c0b21107de/ProjExD/blob/4fb7dd3fee6959ef0d1ef2fd98154c4a6beeaf2f/ex02/calc.py#L17

数字が入っているのかどうかという判定を入れようと思えるということは、既に知識が固まっている前提でしかできない事だと考えました。そして、実際に実装した技術は素晴らしいと思います。改行もコメントも的確で、もう何も言うことはありません。
あなたは技術を持ち、人間に気を配れる素晴らしい人間です。ぜひこのまま、自分のペースでプログラミングをして、地球を美しくしてください。

**Comment by c0b21107de** [comment]
コメントありがとうございます。正規表現での判定です。ぜひ真似してみてください。
