### ISSUE TITLE
Noneの比較について

### ISSUE THREAD

**Issue by Inazuma110** [c0b21107de/ProjExD#9]
https://github.com/c0b21107de/ProjExD/blob/4fb7dd3fee6959ef0d1ef2fd98154c4a6beeaf2f/ex02/calc.py#L17

値がNoneであるかを調べるときは`==`で等値性を見るのではなく，`is`で同一性を見てあげてください．
詳しくはpep8のProgramming Recommendationsなどに書いてあります．
https://peps.python.org/pep-0008/#programming-recommendations

**Comment by Inazuma110** [comment]
「Python None 比較」などで検索すると日本語のわかりやすい記事が出てくると思います

**Comment by c0b21107de** [comment]
コメントありがとうございます。今まで"=="による同値性の比較と"is"の同一性の比較について意識していなかったので非常に参考になる指摘でした。Noneと完全に同じものであることを確認したかったので"is"にすべきだったのだと理解しました。
